set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(XWIN_ROOT "$ENV{HOME}/.local/share/xwin" CACHE PATH "xwin SDK/CRT root")
set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_MT llvm-mt)
set(CMAKE_AR llvm-lib)
set(CMAKE_LINKER lld-link)
set(_includes "")
foreach(dir crt/include sdk/include/ucrt sdk/include/um sdk/include/shared sdk/include/winrt)
    string(APPEND _includes " /imsvc\"${XWIN_ROOT}/${dir}\"")
endforeach()
set(CMAKE_C_FLAGS_INIT "--target=x86_64-pc-windows-msvc ${_includes}")
set(CMAKE_CXX_FLAGS_INIT "--target=x86_64-pc-windows-msvc ${_includes}")
set(_libs "")
foreach(dir crt/lib/x86_64 sdk/lib/um/x86_64 sdk/lib/ucrt/x86_64)
    string(APPEND _libs " /libpath:\"${XWIN_ROOT}/${dir}\"")
endforeach()
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_libs}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_libs}")
set(CMAKE_RC_FLAGS_INIT "-I ${XWIN_ROOT}/sdk/include/um -I ${XWIN_ROOT}/sdk/include/shared -I ${XWIN_ROOT}/crt/include")
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
